# Generated by Django 3.2 on 2021-05-06 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApigeeMgmtLog',
            fields=[
                ('id', models.FloatField(primary_key=True, serialize=False)),
                ('tenant_prefix', models.CharField(blank=True, max_length=10, null=True)),
                ('request_text', models.TextField(blank=True, null=True)),
                ('response_text', models.TextField(blank=True, null=True)),
                ('ip_addr', models.CharField(blank=True, max_length=32, null=True)),
                ('username', models.CharField(blank=True, max_length=256, null=True)),
                ('created_by', models.CharField(blank=True, max_length=256, null=True)),
                ('created_date', models.DateTimeField(auto_now=True, null=True)),
                ('user_roles', models.CharField(blank=True, max_length=1024, null=True)),
                ('build_tags', models.CharField(blank=True, max_length=1024, null=True)),
                ('build_comment', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
