# Generated by Django 3.2 on 2021-05-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_apigeemgmtlog_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='apigeemgmtlog',
            name='destination',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
