/*

 */
 
CREATE TABLE APIGEE_MGMT_ENDPOINT (
    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    ENDPOINT_KEY VARCHAR2(128 CHAR),
    ENDPOINT VARCHAR2(1024 CHAR),
    constraint APIGEE_MGMT_EP_PK primary key (ID),
    constraint APIGEE_MGMT_EP_KEY unique (ENDPOINT_KEY)
);

comment on column APIGEE_MGMT_ENDPOINT.ENDPOINT_KEY is 'unique key for Apigee Management API endpoint';
comment on column APIGEE_MGMT_ENDPOINT.ENDPOINT is 'Apigee Management API endpoint';


CREATE TABLE APIGEE_MGMT_LOG (
    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    TENANT_PREFIX VARCHAR2(10 CHAR),
    REQUEST_TEXT CLOB,
    RESPONSE_TEXT CLOB,
    IP_ADDR VARCHAR2(32 CHAR),
	USERNAME VARCHAR2(256 CHAR),
	CREATED_BY VARCHAR2(256 CHAR),
	CREATED_DATE TIMESTAMP (6),
	USER_ROLES VARCHAR2(1024 CHAR),
	BUILD_TAGS VARCHAR2(1024 CHAR),
	BUILD_COMMENT CLOB,
    constraint APIGEE_MGMT_LOG_PK primary key (ID)
);

comment on column APIGEE_MGMT_LOG.TENANT_PREFIX is 'Tenant prefix derived from API key; supplied by Apigee';
comment on column APIGEE_MGMT_LOG.REQUEST_TEXT is 'Request JSON text for operations within Apigee Management API';
comment on column APIGEE_MGMT_LOG.RESPONSE_TEXT is 'Aggregation of potentially multiple JSON responses from apigee management API related to request';
comment on column APIGEE_MGMT_LOG.IP_ADDR is 'IP Address of requestor; supplied by Apigee';
comment on column APIGEE_MGMT_LOG.USERNAME is 'Username of Apigee user associated with provided API key; supplied by Apigee';
comment on column APIGEE_MGMT_LOG.USER_ROLES is 'Userroles of Apigee user associated with provided API key; supplied by Apigee';
comment on column APIGEE_MGMT_LOG.BUILD_TAGS is 'OPTIONAL comment; supplied by requestor';
comment on column APIGEE_MGMT_LOG.BUILD_COMMENT is 'OPTIONAL comment; supplied by requestor';
